e_lib/urls.py
from django.contrib import admin
from django.urls import path, include
from client import urls as client_urls
from staff import urls as staff_urls
from library import urls as library_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('client/',  include(client_urls)),
    path('staff/',  include(staff_urls)),
    path('library/',  include(library_urls)),
]

library/urls.py
from django.urls import path
from . import views


app_name = 'library'

urlpatterns = [
    path('items/add/', views.add, name='library-add-item'),
    path('items/', views.items, name='library-get-items'),
    path('items/borrow/<int:item_id>/', views.borrow, name='library-borrow-item'),
    path('items/borrowed/<int:user_id>/', views.borrowed, name='library-get-borrowed-items'),
]

library/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class item(models.Model):
    id = models.IntegerField(blank=False, null=False, primary_key=True)
    title = models.CharField(max_length=50, blank=False, null=False)
    author = models.CharField(max_length=50, blank=False, null=False)
    price = models.FloatField(blank=False, null=False)
    available = models.IntegerField(blank=False, null=False, default=0)
    published_on = models.DateField(blank=True, null=True)
    uploaded_on = models.DateTimeField(default=datetime.now)
    summary = models.TextField(blank=True, null=True)
    category = models.ForeignKey('library.category', blank=False, null=False, on_delete=models.CASCADE)
    sub_category = models.IntegerField(blank=False, null=False, default=0)
    item_type = models.ForeignKey('library.item_type', blank=False, null=False, on_delete=models.CASCADE)
    uploaded_by = models.ForeignKey('client.user', blank=False, null=False, on_delete=models.CASCADE)
    deleted_on = models.DateTimeField(blank=True, null=True)
    quantity = models.IntegerField(blank=False, null=False, default=1)
    rating = models.IntegerField(blank=False, null=False, default=3)

    def __str__(self):
        return self.title


class item_type(models.Model):
    id = models.IntegerField(blank=False, null=False, primary_key=True)
    title = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.title


class category(models.Model):
    id = models.IntegerField(blank=False, null=False, primary_key=True)
    title = models.CharField(max_length=50, blank=False, null=False)
    status = models.IntegerField(blank=False, null=False)
    created_on = models.DateTimeField(default=datetime.now)
    update_on = models.DateTimeField(blank=True, null=True)
    deleted_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class sub_category(models.Model):
    id = models.IntegerField(blank=False, null=False, primary_key=True)
    category_id = models.ForeignKey(category, blank=False, null=False, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=False, null=False)
    status = models.IntegerField(blank=False, null=False)
    created_on = models.DateTimeField(default=datetime.now)
    update_on = models.DateTimeField(blank=True, null=True)
    deleted_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class borrowed(models.Model):
    id = models.IntegerField(blank=False, null=False, primary_key=True)
    item = models.ForeignKey(item, blank=False, null=False, on_delete=models.CASCADE)
    user = models.ForeignKey('client.user', blank=False, null=False, on_delete=models.CASCADE)
    borrowed_on = models.DateTimeField(default=datetime.now)
    max_duration = models.IntegerField(blank=False, null=False)
    returned = models.IntegerField(blank=False, null=False, default=-1)

    def __str__(self):
        return str(self.item)

library/views.py
from django.shortcuts import render, redirect
from  e_lib import app_globals 
from  e_lib.app_globals import AppStrings 
from .classes.item import Item
from client.views import check_params, init_context, json_response, new_message
from datetime import datetime

POST = app_globals.POST
GET = app_globals.GET
POSITIVE = app_globals.POSITIVE
NEUTRAL = app_globals.NEUTRAL
NEGATIVE = app_globals.NEGATIVE

def prepare_borrowed(borrowed):
    now = datetime.now().date()
    tbr = []
    for child in borrowed:
        mini = {'item': child.item, 'borrowed_on': child.borrowed_on}
        then = child.borrowed_on.date()
        tdelta = now - then
        mini['days_left'] = child.max_duration - tdelta.days
        tbr.append(mini)

    return tbr

def add(request):
    context = init_context({'id': request.session['staff_user_id']})
    item_types = Item().get_item_types()
    categories = Item().get_categories()

    if item_types['status'] != NEGATIVE:
        context['item_types'] = item_types['item_types']
    
    if categories['status'] != NEGATIVE:
        context['categories'] = categories['categories']
    
    if request.method == POST:
        params_check = check_params(request.POST, { 'published_on': { 'exculded': True }, 'rating': { 'exculded': True }})
        if not params_check['failed']:
            post = request.POST
            staff_id = request.session['staff_id']
            item = Item().add(post['title'], post['author'], post['published_on'], post['category'], post['item_type'], post['price'], post['quantity'], post['rating'], post['summary'], staff_id)
        else:
            context['messages'].extend(params_check['messages'])
    # AppStrings().get_single('no_item_types', 'dict')
    context['app_strings'] = AppStrings().get_multiple(['no_item_types', 'no_categories'])
    return render(request, 'library/add.html', context=context)


def items(request):
    context = init_context()
    items = Item().get(fetch=app_globals.ALL)
    if items['status'] != NEGATIVE:
        context['items'] = items['items']
    context['app_strings'] = AppStrings().get_single('failed_to_get_item', 'dict')
    return render(request, 'library/items.html', context=context)

def borrow(request, item_id):
    context = init_context()
    registration_id = 0
    if 'staff_id' in request.session:
        registration_id = request.session['staff_id']
    elif 'client_id' in request.session:
        registration_id = request.session['client_id']
    borrowed = Item().borrow(item_id, registration_id)
    print(borrowed)

    if 'json' in request.GET:
        return json_response(context)
    else:
        return redirect('library:library-get-items')


def borrowed(request, user_id):
    context = init_context()
    borrowed = Item().get_borrowed_items(user_id)
    if borrowed['status'] != NEGATIVE:
        context['borrowed'] = prepare_borrowed(borrowed['borrowed'])
    
    context['app_strings'] = AppStrings().get_single('failed_to_get_borrowed_items', 'dict')
    if 'json' in request.GET:
        return json_response(context)
    return render(request, 'library/borrowed.html', context=context)

templates/library/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Book</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <div>
            Title <input name="title" id="title" placeholder="Title" required />
        </div>
        <div>
            Author <input name="author" id="author" placeholder="Author" required />
        </div>
        <div>
            Published On <input name="published_on" id="published_on" placeholder="Published On" type="date" />
        </div>
        <div>
            Item Type
            <div>
                <select name="item_type">
                    {% if item_types %}
                        {% for item_type in item_types %}
                            <option value="{{item_type.id}}">{{item_type.title}}</option>
                        {% endfor %}
                    {% else %}
                        <option value="0">{{app_strings.no_item_types}}</option>
                    {% endif %}
                </select>
            </div>
        </div>
        <div>
            Category {{app_strings}}
            <div>
                <select name="category">
                    {% if categories %}
                        {% for category in categories %}
                            <option value="{{category.id}}">{{category.title}}</option>
                        {% endfor %}
                    {% else %}
                        <option value="0">{{app_strings.no_categories}}</option>
                    {% endif %}
                </select>
            </div>
        </div>
        <div>
            Price <input name="price" id="price" placeholder="Price" type="number" required />
        </div>
        <div>
            Quantity <input name="quantity" id="quantity" placeholder="Quantity" type="number" required />
        </div>
        <div>
            Rating
            <select name="rating">
                <option value="1">1 star</option>
                <option value="2">2 star</option>
                <option value="3">3 star</option>
                <option value="4">4 star</option>
                <option value="5">5 star</option>
            </select>
        </div>
        <div>
            Summary <textarea name="summary" id="summary" cols="40" rows="5" placeholder="Enter a brief summary"></textarea>
        </div>
        <div>
            <button type="submit">Submit</button>
        </div>
    </form>
</body>
</html>

templates/library/borrowed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widt h=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Items</title>
</head>
<body>
    <table>
        <tr>
            <th>Type</th>
            <th>Title</th>
            <th>Author</th> 
            <th>Borrowed on</th>
            <th>Days left</th>
            <th>Returned</th>
        </tr>
        {% if borrowed %}
            {% for child in borrowed %}
                <tr>
                    <td>{{child.item.item_type}}</td>
                    <td>{{child.item.title}}</td>
                    <td>{{child.item.author}}</td>
                    <td>{{child.borrowed_on}}</td>
                    <td>{{child.days_left}}</td>
                    <td>
                        {% if child.returned == -1 %}
                            No
                        {% else %}
                            Yes
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>{{app_strings.failed_to_get_borrowed_items}}</td>
            </tr>
        {% endif %}
        
    </table>
</body>
</html>

templates/library/items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widt h=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Items</title>
</head>
<body>
    <table>
        <tr>
            <th>Type</th>
            <th>Title</th>
            <th>Author</th>
            <th>Category</th>
            <th>Price</th>
            <th>published_on</th>
            <th></th>
        </tr>
        {% if items %}
            {% for item in items %}
                <tr>
                    <td>{{item.item_type}}</td>
                    <td>{{item.title}}</td>
                    <td>{{item.author}}</td>
                    <td>{{item.category}}</td>
                    <td>{{item.price}}</td>
                    <td>{{item.published_on}}</td>
                    <td>
                        {% if item.quantity > 0 %}
                            <a href="{% url 'library:library-borrow-item' item.id %}">Borrow</a>
                        {% else %}
                            Unavailable
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        {% else %}
                <tr>
                    <td>{{app_strings.failed_to_get_item}}</td>
                </tr>
        {% endif %}
        
    </table>
</body>
</html>